import { useState, useMemo } from "react";
import "./SupportedSitesPage.css";

// Popular/commonly used sites organized by category
const FEATURED_SITES = {
  "Video Platforms": [
    { name: "YouTube", domain: "youtube.com", icon: "🎬" },
    { name: "Vimeo", domain: "vimeo.com", icon: "🎥" },
    { name: "Dailymotion", domain: "dailymotion.com", icon: "📺" },
    { name: "Twitch", domain: "twitch.tv", icon: "🎮" },
    { name: "Rumble", domain: "rumble.com", icon: "📹" },
    { name: "Odysee", domain: "odysee.com", icon: "🌊" },
    { name: "PeerTube", domain: "peertube.tv", icon: "🔗" },
    { name: "Bitchute", domain: "bitchute.com", icon: "📡" },
  ],
  "Social Media": [
    { name: "Twitter/X", domain: "x.com", icon: "🐦" },
    { name: "Instagram", domain: "instagram.com", icon: "📸" },
    { name: "TikTok", domain: "tiktok.com", icon: "🎵" },
    { name: "Facebook", domain: "facebook.com", icon: "👤" },
    { name: "Reddit", domain: "reddit.com", icon: "🤖" },
    { name: "LinkedIn", domain: "linkedin.com", icon: "💼" },
    { name: "Threads", domain: "threads.net", icon: "🧵" },
    { name: "Bluesky", domain: "bsky.app", icon: "🦋" },
  ],
  "Music & Audio": [
    { name: "SoundCloud", domain: "soundcloud.com", icon: "🎧" },
    { name: "Bandcamp", domain: "bandcamp.com", icon: "🎸" },
    { name: "Mixcloud", domain: "mixcloud.com", icon: "🎛️" },
    { name: "Audiomack", domain: "audiomack.com", icon: "🎤" },
  ],
  "News & Media": [
    { name: "BBC", domain: "bbc.co.uk", icon: "📰" },
    { name: "CNN", domain: "cnn.com", icon: "🗞️" },
    { name: "NBC", domain: "nbc.com", icon: "📺" },
    { name: "CBS", domain: "cbsnews.com", icon: "📻" },
    { name: "ABC", domain: "abc.net.au", icon: "🎙️" },
    { name: "NPR", domain: "npr.org", icon: "🎧" },
  ],
  Educational: [
    { name: "TED", domain: "ted.com", icon: "💡" },
    { name: "Khan Academy", domain: "khanacademy.org", icon: "📚" },
    { name: "Coursera", domain: "coursera.org", icon: "🎓" },
    { name: "Udemy", domain: "udemy.com", icon: "📖" },
  ],
  "Streaming Services": [
    { name: "Crunchyroll", domain: "crunchyroll.com", icon: "🍥" },
    { name: "Nebula", domain: "nebula.tv", icon: "🌌" },
    { name: "Dropout", domain: "dropout.tv", icon: "🎭" },
    { name: "CuriosityStream", domain: "curiositystream.com", icon: "🔬" },
  ],
};

// Extended list of all supported sites (yt-dlp extractors)
const ALL_SITES = [
  "1News",
  "1tv",
  "23video",
  "24video",
  "3qsdn",
  "3sat",
  "4tube",
  "56.com",
  "5min",
  "7digital",
  "7plus",
  "8tracks",
  "91porn",
  "9c9media",
  "9gag",
  "9now",
  "abc.net.au",
  "abcnews",
  "abcotvs",
  "academia",
  "acast",
  "adn",
  "adobeconnect",
  "adobetv",
  "adultswim",
  "aenetworks",
  "afreecatv",
  "agora",
  "airmozilla",
  "aitube",
  "akvideo",
  "aliexpress",
  "allocine",
  "alphaporno",
  "alura",
  "amara",
  "amazon",
  "americastestkitchen",
  "amp",
  "anchor",
  "angel",
  "animeondemand",
  "antenna",
  "anvato",
  "aol",
  "apa",
  "aparat",
  "appleconnect",
  "applepodcasts",
  "appletrailers",
  "archive.org",
  "arcpublishing",
  "ard",
  "arkena",
  "arnes",
  "art19",
  "arte",
  "asobistage",
  "asstmedia",
  "atresplayer",
  "atvat",
  "audible",
  "audioboom",
  "audiomack",
  "audius",
  "awaan",
  "axs",
  "azmedien",
  "baidu",
  "bandaichannel",
  "bandcamp",
  "bannedvideo",
  "bbc",
  "beatport",
  "beeg",
  "behindkink",
  "bellmedia",
  "bet",
  "bfi",
  "bfmtv",
  "bibeltv",
  "bigflix",
  "bigo",
  "bilibili",
  "biobiochiletv",
  "bitchute",
  "blackboardcollaborate",
  "bleacherreport",
  "blogger",
  "bloomberg",
  "bokecc",
  "bongacams",
  "bostonglobe",
  "box",
  "bpb",
  "br",
  "brainpop",
  "bravotv",
  "breakcom",
  "breitbart",
  "brightcove",
  "brmedia",
  "bt",
  "businessinsider",
  "buzzfeed",
  "byutv",
  "c56",
  "cableav",
  "callin",
  "caltrans",
  "cam4",
  "camdemy",
  "camfm",
  "cammodels",
  "camwithher",
  "canalc2",
  "canalplus",
  "canvas",
  "carambatv",
  "cartoonnetwork",
  "cbc",
  "cbs",
  "cbsinteractive",
  "cbslocal",
  "cbsnews",
  "cbssports",
  "ccc",
  "ccma",
  "cctv",
  "cda",
  "cellebrite",
  "ceskatelevize",
  "cgtn",
  "channel9",
  "chilloutzone",
  "chirbit",
  "cinchcast",
  "cinemax",
  "cinetecamilano",
  "cjsw",
  "cliphunter",
  "clippit",
  "cliprs",
  "clipsyndicate",
  "closertotruth",
  "cloudflarestream",
  "cloudy",
  "clubic",
  "clyp",
  "cmt",
  "cnbc",
  "cnn",
  "comedycentral",
  "commonmistakes",
  "conanclassic",
  "condenast",
  "corus",
  "coub",
  "cozytv",
  "cpac",
  "cracked",
  "crackle",
  "craftsy",
  "crooksandliars",
  "crowdbunker",
  "crtvg",
  "crunchyroll",
  "cspan",
  "ctsnews",
  "ctvnews",
  "curiositystream",
  "cwtv",
  "cybrary",
  "dacast",
  "dailymail",
  "dailymotion",
  "dailywire",
  "damtomo",
  "daum",
  "dbtv",
  "dctp",
  "deezer",
  "democracynow",
  "dfb",
  "dhm",
  "digg",
  "digitalconcerthall",
  "discovery",
  "discoverygo",
  "disney",
  "dlf",
  "dlive",
  "doodstream",
  "dotsub",
  "douyutv",
  "dplay",
  "drbonanza",
  "dropbox",
  "dropout",
  "drtuber",
  "drtv",
  "dtube",
  "duboku",
  "dvtv",
  "dw",
  "eagleplatform",
  "ebaumsworld",
  "echomsk",
  "egghead",
  "ehftv",
  "einthusan",
  "eitb",
  "elevensports",
  "ellentube",
  "elpais",
  "embedly",
  "engadget",
  "eporner",
  "erocast",
  "eroprofile",
  "escapist",
  "espn",
  "esri",
  "europa",
  "europeantour",
  "eurosport",
  "euscreen",
  "expotv",
  "expressen",
  "extremetube",
  "eyedotv",
  "facebook",
  "fancodevisio",
  "fanserialstv",
  "faz",
  "fc2",
  "fczenit",
  "filmon",
  "filmweb",
  "firsttv",
  "fite",
  "flickr",
  "floatplane",
  "folketinget",
  "footyroom",
  "formula1",
  "fox",
  "fox9",
  "foxgay",
  "foxnews",
  "foxsports",
  "franceculture",
  "franceinter",
  "francetv",
  "freesound",
  "freespeech",
  "freetv",
  "frontendmasters",
  "funimation",
  "funk",
  "funnyordie",
  "fux",
  "fxnetworks",
  "gab",
  "gaia",
  "gameinformer",
  "gamejolt",
  "gamespot",
  "gamestar",
  "gaskrank",
  "gazeta",
  "gdcvault",
  "generic",
  "genericembeds",
  "gettr",
  "gfycat",
  "giantbomb",
  "giga",
  "giphy",
  "glide",
  "globo",
  "glomex",
  "gmanetwork",
  "go",
  "godtube",
  "gofile",
  "golem",
  "goodgame",
  "googledrive",
  "googlepodcasts",
  "googlesearch",
  "goshgay",
  "gotostage",
  "gputechconf",
  "gronkh",
  "groupon",
  "harpodeon",
  "hbo",
  "hearthis",
  "heise",
  "hellporno",
  "helsinki",
  "hentaistigma",
  "hidive",
  "historicfilms",
  "hitbox",
  "hitrecord",
  "hketv",
  "hollywoodreporter",
  "hooktube",
  "hornbunny",
  "hotnewhiphop",
  "hotstar",
  "howcast",
  "howstuffworks",
  "hrfernsehen",
  "hrti",
  "huajiao",
  "huffpost",
  "hungama",
  "huya",
  "hypem",
  "hytale",
  "icareus",
  "ichinanalive",
  "ign",
  "iheart",
  "ilpost",
  "imdb",
  "imgur",
  "ina",
  "inc",
  "indavideo",
  "infoq",
  "instagram",
  "internazionale",
  "iqiyi",
  "itprotv",
  "itv",
  "ivideon",
  "iwara",
  "ixigua",
  "izlesene",
  "jamendo",
  "jeuxvideo",
  "jiocinema",
  "joj",
  "jove",
  "jwplatform",
  "kakao",
  "kaltura",
  "kanalplay",
  "kankan",
  "karaoketv",
  "karrierevideos",
  "keezmovies",
  "kelbyone",
  "ketnet",
  "khanacademy",
  "kick",
  "kickstarter",
  "kinja",
  "kinopoisk",
  "konserthusetplay",
  "koo",
  "krasview",
  "kth",
  "ku6",
  "kuwo",
  "la7",
  "laola1tv",
  "lbry",
  "lci",
  "lcp",
  "lecture2go",
  "lecturio",
  "leeco",
  "lego",
  "lemonde",
  "lenta",
  "libraryofcongress",
  "libsyn",
  "lifenews",
  "likee",
  "limelight",
  "linkedin",
  "linuxacademy",
  "liputan6",
  "listennotes",
  "litv",
  "livejournal",
  "livestream",
  "lnkgo",
  "localnews8",
  "loom",
  "lovehomeporn",
  "lrt",
  "lsm",
  "lumni",
  "lynda",
  "m6",
  "madthumbs",
  "magentamusik",
  "mailru",
  "mainstreaming",
  "makeagif",
  "managobang",
  "mangomolo",
  "manoto",
  "manyvids",
  "maoritv",
  "markiza",
  "massengeschmacktv",
  "masters",
  "matchtv",
  "mdr",
  "mediaite",
  "medialaan",
  "mediaset",
  "mediasite",
  "medici",
  "megaphone",
  "megatvcom",
  "meipai",
  "melonvod",
  "metacafe",
  "metacritic",
  "mgoon",
  "mgtv",
  "microsoftstream",
  "microsoftvirtualacademy",
  "mildom",
  "minds",
  "ministrygrid",
  "minoto",
  "miomio",
  "mirrativ",
  "mit",
  "mitele",
  "mixch",
  "mixcloud",
  "mlb",
  "mlssoccer",
  "mms",
  "mnet",
  "mocha",
  "moevideo",
  "mofosex",
  "mojvideo",
  "monstercat",
  "motherless",
  "motorsport",
  "movieclips",
  "moviepilot",
  "moviezine",
  "movingimage",
  "msn",
  "mtv",
  "muenchentv",
  "mwave",
  "mxplayer",
  "mychannels",
  "myspace",
  "myspass",
  "myvi",
  "myvideo",
  "mzaalo",
  "n1",
  "nate",
  "nationalgeographic",
  "naver",
  "nba",
  "nbc",
  "nbcnews",
  "nbcolympics",
  "nbcsports",
  "nbcstations",
  "ndr",
  "ndtv",
  "nebula",
  "nerdcubed",
  "neteasemusic",
  "netzkino",
  "newgrounds",
  "newspicks",
  "newstube",
  "newsy",
  "nextmedia",
  "nexx",
  "nfb",
  "nfhsnetwork",
  "nfl",
  "nhk",
  "nhl",
  "nick",
  "niconico",
  "ninecninemedia",
  "ninegag",
  "ninenow",
  "nintendo",
  "nitter",
  "njpwworld",
  "nobelprize",
  "noco",
  "nonktube",
  "noodlemagazine",
  "noovo",
  "normalboots",
  "nosvideo",
  "nova",
  "novaplay",
  "nowness",
  "noz",
  "npo",
  "npr",
  "nrk",
  "ntv",
  "ntvru",
  "nuevo",
  "nuvid",
  "nytimes",
  "nzherald",
  "nzonscreen",
  "odatv",
  "odnoklassniki",
  "odysee",
  "offtv",
  "oktoberfesttv",
  "olympics",
  "on24",
  "ondemandkorea",
  "onet",
  "onionstudios",
  "ooyala",
  "openload",
  "orf",
  "outsidetv",
  "packtpub",
  "palcomp3",
  "pandatv",
  "pandoratv",
  "parliamentliveuk",
  "patreon",
  "pbs",
  "pbskids",
  "pcmag",
  "pearvideo",
  "peertube",
  "people",
  "performgroup",
  "periscope",
  "philharmoniedeparis",
  "phoenix",
  "photobucket",
  "picarto",
  "piksel",
  "pinkbike",
  "pinterest",
  "pladform",
  "platzi",
  "playfm",
  "plays",
  "playstuff",
  "playsuisse",
  "playvid",
  "playwire",
  "pluralsight",
  "plus7",
  "podomatic",
  "pokemon",
  "politico",
  "polsatgo",
  "polskieradio",
  "porncom",
  "pornflip",
  "pornhub",
  "pornotube",
  "pornovoisines",
  "pornoxo",
  "puhutv",
  "pr0gramm",
  "prankcast",
  "premiershiprugby",
  "presstv",
  "projectveritas",
  "prosiebensat1",
  "puls4",
  "pyvideo",
  "qqmusic",
  "r7",
  "radiko",
  "radiobremen",
  "radiode",
  "radiofrance",
  "radiojavan",
  "radlive",
  "rai",
  "rbgtum",
  "rbn",
  "rcs",
  "rcti",
  "rds",
  "redbulltv",
  "reddit",
  "redgifs",
  "redtube",
  "regiotv",
  "rentv",
  "restudy",
  "reuters",
  "reverbnation",
  "rice",
  "rmcdecouverte",
  "rockstargames",
  "roosterteeth",
  "rottentomatoes",
  "roxwel",
  "rozhlas",
  "rte",
  "rtp",
  "rtrfm",
  "rts",
  "rtve",
  "rtvnh",
  "rtvs",
  "ruhd",
  "rule34video",
  "rumble",
  "rutube",
  "ruutu",
  "ruv",
  "safari",
  "saitosan",
  "samplefocus",
  "sapo",
  "savefrom",
  "sbs",
  "screen9",
  "screencast",
  "screencastomatic",
  "scrippsnetworks",
  "scte",
  "seeker",
  "senategov",
  "sendtonews",
  "servus",
  "sevenplus",
  "sexu",
  "seznamzpravy",
  "shahid",
  "shared",
  "sharevideos",
  "shemaroome",
  "showroomlive",
  "simplecast",
  "sina",
  "skyit",
  "skylinewebcams",
  "skynewsarabia",
  "skynewsau",
  "slideshare",
  "slideslive",
  "slutload",
  "snotr",
  "sohu",
  "sonyliv",
  "soundcloud",
  "soundgasm",
  "southpark",
  "spankbang",
  "spankwire",
  "spiegel",
  "spiegeltv",
  "sport5",
  "sportbox",
  "sportdeutschland",
  "spotify",
  "spreaker",
  "springboardplatform",
  "sprout",
  "srgssr",
  "srmediathek",
  "stanfordoc",
  "startv",
  "steam",
  "stitcher",
  "storyfire",
  "streamable",
  "streamcz",
  "streetvoice",
  "stretchinternet",
  "stripchat",
  "stv",
  "sunporno",
  "sverigesradio",
  "svt",
  "swrmediathek",
  "syfy",
  "sztvhu",
  "t13",
  "tagesschau",
  "tass",
  "tbs",
  "tbsjp",
  "teachable",
  "teachertube",
  "teachingchannel",
  "teamcoco",
  "teamtreehouse",
  "techtalks",
  "techtv",
  "ted",
  "tele13",
  "telebruxelles",
  "telecinco",
  "telegraaf",
  "telegram",
  "telemb",
  "telemundo",
  "telequebec",
  "teletask",
  "telewebion",
  "tennistv",
  "tenplay",
  "testurl",
  "tf1",
  "tfo",
  "theintercept",
  "theplatform",
  "thescene",
  "thestar",
  "thesun",
  "theweatherchannel",
  "thisamericanlife",
  "thisav",
  "thisoldhouse",
  "threeqsdn",
  "tiktok",
  "tinypic",
  "tmz",
  "tnaflix",
  "toggle",
  "tonline",
  "toongoggles",
  "tou",
  "toutvqc",
  "toypics",
  "traileraddict",
  "trilulilu",
  "trovo",
  "truetv",
  "trunews",
  "trutv",
  "tube8",
  "tubetugraz",
  "tubitv",
  "tumblr",
  "tunein",
  "tunepk",
  "turbo",
  "tv2",
  "tv2dk",
  "tv2hu",
  "tv4",
  "tv5mondeplus",
  "tv5unis",
  "tva",
  "tvanouvelles",
  "tvc",
  "tver",
  "tvland",
  "tvn24",
  "tvnet",
  "tvnoe",
  "tvnow",
  "tvopengr",
  "tvp",
  "tvplay",
  "tvplayer",
  "tweakers",
  "twentyfourvideo",
  "twentymin",
  "twentythreevideo",
  "twitcasting",
  "twitch",
  "twitter",
  "udemy",
  "ufctv",
  "ukcolumn",
  "uktvplay",
  "umg",
  "unistra",
  "unity",
  "uol",
  "uplynk",
  "urort",
  "urplay",
  "usanetwork",
  "usatoday",
  "ustream",
  "ustudio",
  "varzesh3",
  "vbox7",
  "veehd",
  "veo",
  "veoh",
  "vesti",
  "vevo",
  "vgtv",
  "vh1",
  "vice",
  "vidbit",
  "viddler",
  "videa",
  "video.sky.it",
  "videodetective",
  "videofyme",
  "videoken",
  "videomore",
  "videopress",
  "vidio",
  "vidlii",
  "vidme",
  "vidzi",
  "vier",
  "viewlift",
  "viidea",
  "viki",
  "vimeo",
  "vimple",
  "vine",
  "viqeo",
  "virgin",
  "viu",
  "vivo",
  "vk",
  "vlive",
  "vodlocker",
  "vodpl",
  "vodplatform",
  "voicerepublic",
  "voot",
  "voxmedia",
  "vrak",
  "vrt",
  "vrv",
  "vshare",
  "vtm",
  "vube",
  "vuclip",
  "vupload",
  "vvvvid",
  "vyborymos",
  "vzaar",
  "wakanim",
  "walla",
  "washingtonpost",
  "wat",
  "watchbox",
  "watchindianporn",
  "wdr",
  "webcaster",
  "webofstories",
  "weibo",
  "weiqitv",
  "whatshouldicallme",
  "wholecloud",
  "whowatch",
  "wistia",
  "wnl",
  "wordpress",
  "worldstarhiphop",
  "wppilot",
  "wrestleuniverse",
  "wsj",
  "wwe",
  "wykop",
  "xboxclips",
  "xfileshare",
  "xhamster",
  "xiaohongshu",
  "ximalaya",
  "xinpianchang",
  "xminus",
  "xnxx",
  "xstream",
  "xtube",
  "xuite",
  "xvideos",
  "xxxymovies",
  "yahoo",
  "yandexdisk",
  "yandexmusic",
  "yandexvideo",
  "yapfiles",
  "yesjapan",
  "yinyuetai",
  "ynet",
  "youjizz",
  "youku",
  "younow",
  "youporn",
  "yourporn",
  "yourupload",
  "youtube",
  "youtubeannotations",
  "yoyo",
  "zaiko",
  "zapiks",
  "zaq1",
  "zattoo",
  "zdf",
  "zee5",
  "zhihu",
  "zingmp3",
  "zoom",
  "zype",
];

export default function SupportedSitesPage() {
  const [searchQuery, setSearchQuery] = useState("");
  const [activeCategory, setActiveCategory] = useState("all");

  const filteredAllSites = useMemo(() => {
    if (!searchQuery) return ALL_SITES;
    return ALL_SITES.filter((site) =>
      site.toLowerCase().includes(searchQuery.toLowerCase())
    );
  }, [searchQuery]);

  const categories = ["all", ...Object.keys(FEATURED_SITES)];

  return (
    <div className="supported-sites-page">
      <div className="page-header">
        <h1>Supported Sites</h1>
        <p className="page-subtitle">
          Download from 1,700+ websites powered by yt-dlp
        </p>
      </div>

      {/* Search */}
      <div className="search-container">
        <div className="search-input-wrapper">
          <span className="search-icon">🔍</span>
          <input
            type="text"
            className="search-input"
            placeholder="Search sites..."
            value={searchQuery}
            onChange={(e) => setSearchQuery(e.target.value)}
          />
          {searchQuery && (
            <button
              className="clear-search"
              onClick={() => setSearchQuery("")}
              aria-label="Clear search"
            >
              ✕
            </button>
          )}
        </div>
        <p className="search-results-count">
          {searchQuery
            ? `Found ${filteredAllSites.length} sites`
            : `${ALL_SITES.length} sites available`}
        </p>
      </div>

      {/* Featured Sites by Category */}
      {!searchQuery && (
        <section className="featured-section">
          <h2>Popular Sites</h2>

          {/* Category Tabs */}
          <div className="category-tabs">
            {categories.map((category) => (
              <button
                key={category}
                className={`category-tab ${
                  activeCategory === category ? "active" : ""
                }`}
                onClick={() => setActiveCategory(category)}
              >
                {category === "all" ? "All" : category}
              </button>
            ))}
          </div>

          {/* Featured Sites Grid */}
          <div className="featured-grid">
            {activeCategory === "all"
              ? Object.entries(FEATURED_SITES).map(([category, sites]) =>
                  sites.map((site) => (
                    <div key={site.name} className="featured-card">
                      <span className="site-icon">{site.icon}</span>
                      <div className="site-info">
                        <span className="site-name">{site.name}</span>
                        <span className="site-domain">{site.domain}</span>
                      </div>
                    </div>
                  ))
                )
              : FEATURED_SITES[activeCategory]?.map((site) => (
                  <div key={site.name} className="featured-card">
                    <span className="site-icon">{site.icon}</span>
                    <div className="site-info">
                      <span className="site-name">{site.name}</span>
                      <span className="site-domain">{site.domain}</span>
                    </div>
                  </div>
                ))}
          </div>
        </section>
      )}

      {/* All Sites List */}
      <section className="all-sites-section">
        <h2>{searchQuery ? "Search Results" : "All Supported Sites"}</h2>
        <p className="section-subtitle">
          Complete list of extractors supported by yt-dlp
        </p>

        <div className="sites-grid">
          {filteredAllSites.map((site) => (
            <div key={site} className="site-tag">
              {site}
            </div>
          ))}
        </div>

        {filteredAllSites.length === 0 && (
          <div className="no-results">
            <span className="no-results-icon">🔍</span>
            <p>No sites found matching "{searchQuery}"</p>
            <p className="no-results-hint">
              Try a different search term, or the site may use a generic
              extractor
            </p>
          </div>
        )}
      </section>

      {/* Info Note */}
      <div className="info-note">
        <span className="info-icon">ℹ️</span>
        <div>
          <strong>Note:</strong> This list may not be exhaustive. Many sites
          work through generic extractors. If a site isn't listed, try pasting
          the URL anyway—it might still work!
        </div>
      </div>
    </div>
  );
}
